#!/usr/bin/env python3
"""Content-anchored compression of the manuscript body.

Each entry is (anchor, new_text). The script finds the UNIQUE paragraph whose
normalised text starts with `anchor` and replaces it; an anchor that matches
zero or more than one paragraph raises, so the batch cannot silently hit the
wrong block. `new_text == ''` deletes the paragraph. Empty paragraphs left
behind by deletions are dropped at the end.

This replaces the earlier line-number batches, which silently corrupted
Section 3.2 when a previous batch had shifted the line numbering.
"""
import sys

MAIN = sys.argv[1] if len(sys.argv) > 1 else 'main.tex'
R = []          # (anchor, new text)


def add(anchor, new):
    R.append((anchor, new))


# ------------------------------------------------------------------ §1
add('Selective state-space models (SSMs) have recently become',
    r"""Selective state-space models (SSMs) have become a backbone of infrared--visible image fusion because their linear-time global receptive field scales better than self-attention on large inputs \cite{ma2025s4fusion,gu2023mamba}. Their usefulness at high resolution is constrained by state capacity: the recurrent state is bounded, long sequences dilute what each slot retains --- beyond that capacity the model fails even to learn what to forget \cite{chen2025stuffed} --- and the transition is governed by the decay matrix's spectral properties, so poorly managed states drift or vanish \cite{lu2025mambamodulation,ali2025hidden}. Hence the hypothesis that high-resolution fusion failures originate \emph{inside} the state dynamics: that injecting per-pixel boundary reliability into the selective parameters $B$, $C$ and $\Delta$ would re-allocate capacity toward modality boundaries.""")

add('We tested it under controlled conditions',
    r"""We tested it under controlled conditions --- every configuration fine-tuned from the same public S4Fusion weights, same budget, same overlap-tiled inference protocol on M3FD \cite{liu2022tardal} --- and the result is a falsification that does not survive repetition. On seed 42 the state-modulated model significantly \emph{degraded} the structural metrics (SF $-0.019$, AG $-0.013$, QABF $-0.0005$, Holm $p < 0.05$); a second seed meets the same criterion in the \emph{opposite} direction (SF $+0.033$, AG $+0.017$), a third degrades only the QABF median, and the one quantity stable across all three is that median, down by $0.0005$. Under this parameterization feature-space modulation of the state dynamics is therefore neither established nor excluded, and the pivot below rests on the design argument of Section~\ref{sec:methods:problem} rather than on this arm.""")

add('Where the two modalities disagree --- opposite edge orientation',
    r"""Where the two modalities disagree --- opposite edge orientation or polarity at a pixel --- a local convex combination of the two \emph{registered source images} cancels structure, whereas committing to the locally salient modality preserves it; Section~\ref{sec:methods:problem} states the conditions, and notes that this is a statement about a pointwise image-space operator rather than a general property of feature-space fusion. An exploratory training-free check pointed the same way --- committing toward the max-response modality recovered objects that blending loses --- and we record it as a \emph{pilot}, since it predates this study's freeze and has no frozen method record; no result here depends on it. We therefore introduce \textbf{Commitment-Gated Arbitration (CGA)}: it detects per-pixel modal conflict from image gradients, learns a per-pixel commitment toward the salient modality, and applies it through a zero-initialized gate, so that loading the official checkpoint reproduces the baseline exactly \cite{bachlechner2021rezero}. The part of CGA that carried its argument is the restriction of commitment to conflict regions, and Section~\ref{sec:exp:controls} tests it --- with the result that the restriction is \emph{not} supported: an all-ones map raises high-conflict recall above the learned map while lowering mAP50 below it, and permuting the conflict map changes nothing measurable.""")

add('S4Fusion is the testbed because it is an open, published',
    r"""S4Fusion is the testbed because it is an open published selective state-space backbone whose released weights make the comparison \emph{controlled}, and because the zero-initialized gate validates the module \emph{against} the weights it modifies. The study is scoped to it; no claim is made that its behaviour typifies scan-based fusion backbones as a class (Section~\ref{sec:limitations}). The mechanism is reported as built and active at inference, and the restriction that motivated it as empirically unsupported; the two claims stay apart throughout.""")

add('Four things, none of them a performance claim',
    r"""Four things, none of them a performance claim. \emph{First, a zero-initialized image-space adapter compatible with the weights it modifies}: a per-pixel source-selection network combined with the backbone's fused image through one zero-initialized scalar gate, so the augmented model reproduces the official checkpoint exactly at load time and its effect is measured only after training opens the gate (Sections~\ref{sec:methods:cga}--\ref{sec:methods:training}). \emph{Second, a falsification that does not itself replicate}: the intervention the literature's capacity diagnosis implies fails the structural criterion on the seed it was run on, meets the same criterion in the opposite direction on a second, and is reproduced in full by a content-free reliability map, so its effect is not a property of boundary reliability at all (Section~\ref{sec:exp:verdicts}). \emph{Third, the separation of the trained selector from the parameter-free rules it resembles}: the benefit does not replicate, but the operator is not free --- seven parameter-free rules on two supports are each worse than the learned selector at the detection endpoint, and the sharpest, the same architecture with only the selector reset, is slightly worse than doing nothing (Table~\ref{tab:free}). \emph{Fourth, a protocol}: criterion layering, both base conventions reported as non-comparable, replication counted per seed, and a cluster-aware re-analysis that treats the image rather than the object as the unit of observation (Sections~\ref{sec:methods:design} and~\ref{sec:exp:verdicts}). The protocol is what turns a weak result into a legible one, and it is the part of this work most directly reusable.""")

# ------------------------------------------------------------------ §2
add('CNN fusion builds on autoencoder and dense designs',
    r"""CNN fusion builds on autoencoder and dense designs (DenseFuse \cite{li2019densefuse}, FusionDN \cite{xu2020fusiondn}, U2Fusion \cite{xu2022u2fusion}) and on adversarial generation (FusionGAN \cite{ma2019fusiongan}); Transformer fusion added global context (CDDFuse \cite{zhao2023cddfuse}, MetaFusion \cite{zhao2023metafusion}, EMMA \cite{zhao2024equivariant}), and diffusion fusion casts the problem as iterative denoising (DDFM \cite{zhao2023ddfm}, Diff-IF \cite{yi2024diffif}). Across all three families the operator remains a weighted combination of modality evidence: at a pixel where the sources disagree the network chooses how much of each to mix rather than deciding which to trust.""")

add('Selective state spaces entered IVIF nearly simultaneously',
    r"""Selective state spaces entered IVIF nearly simultaneously --- S4Fusion \cite{ma2025s4fusion}, the wavelet-domain W-Mamba \cite{zhang2025wmamba} and the multi-modal FusionMamba \cite{xie2024fusionmamba} --- inheriting linear-time global context from the SSM family \cite{gu2023mamba,dao2024transformers}, and their limitation is state capacity: an overloaded recurrent state loses its ability to manage what it retains \cite{chen2025stuffed}, and only the A/$\Delta$ parameters govern history decay \cite{ali2025hidden,lu2025mambamodulation}. In the implementations we reviewed they scan and blend rather than select, and the 2026 wave modifies \emph{scan topology} \cite{zhu2026interactive,cao2026shuffle,wang2026selfsupervised}, i.e.\ \emph{where the scan looks}. Our own ablation (Section~\ref{sec:methods:design}) finds that modulating the state dynamics with boundary reliability does not improve structural metrics under its parameterization, which is why what we test instead is a selection decision at conflicting pixels.""")

add('Task-awareness improves fusion for perception',
    r"""Task-guided fusion --- SeAFusion \cite{tang2022seafusion}, SegMiF/M2Fusion \cite{liu2023segmif}, MetaFusion \cite{zhao2023metafusion} and lightweight KD variants \cite{zhao2023lightweight,wang2025semantic} --- guides \emph{where} to look while still weighting features at conflicting pixels and needs task labels at inference. Boundary and uncertainty cues are an active direction (BUFNet \cite{zhou2026bufnet}, ShadowMamba \cite{zhu2026shadowmamba}, edge-prior-guided IVIF \cite{yuan2025segment}, edge-guided dual attention \cite{zou2023lightweight}, uncertainty-aware detection fusion \cite{zhao2024uncertainty}).""")

add('Closest to our setting, ARC3Fusion',
    r"""Closest to our setting, ARC3Fusion \cite{tian2026adaptive} models consensus--complementarity--\emph{conflict} in IVIF and GatedFusion-Net \cite{brenner2026gatedfusion} computes per-pixel modality weights, but both are \emph{continuous, feature-space} coordinators: three-branch Softmax weights summing to one, and per-pixel Sigmoid masks. Image-space per-pixel \emph{hard} selection has a separate lineage --- the classical select/choose rules \cite{burt1993enhanced,zhang1999categorization,piella2003general} and the learning-based multi-focus decision-map line \cite{ma2021endtoend} --- but same-modality and defocus-driven. Learned \emph{discrete} routing has also entered IVIF: a concurrent preprint \cite{ma2026dynamic} selects among three experts per pixel via a Gumbel-Softmax straight-through estimator, the closest existing instance of per-pixel hard choice in cross-modal fusion, though it operates on feature components and routes on learned informativeness rather than cross-modal gradient conflict. To the best of our knowledge no prior IVIF method converts cross-modal gradient-orientation conflict into a learned, image-space, per-pixel hard selection. That is a statement of absence in the literature we reviewed, not a proof of novelty, and the characterizations differ in verification depth: the two published neighbours were read in full, while the concurrent preprint was verified at abstract level only, so nothing is asserted about its unstated components.""")

# --------------------------------------------------------------- §3.1
add('We define cross-modal conflict at a pixel',
    r"""We define cross-modal conflict at a pixel as the conjunction of two conditions: both modalities carry structure there, and their gradient vectors disagree in orientation or polarity --- the common case at modality boundaries, where a thermal edge and its visible counterpart often have opposite polarity. The argument is made under three explicit conditions: the sources are \emph{registered}, the comparison is \emph{local}, and the operator is a \emph{pointwise convex combination of the two source images} rather than of any intermediate feature tensor. Under those conditions a combination is structurally destructive at a conflicting pixel: if locally $\nabla I_{\mathrm{vi}} \approx -\nabla I_{\mathrm{ir}}$ with common magnitude $g$, then $F = w\,I_{\mathrm{ir}} + (1-w)\,I_{\mathrm{vi}}$ has gradient magnitude $|\nabla F| \approx |2w-1|\,g$, which vanishes at $w = 1/2$ and is preserved only at the endpoints. For arbitrary magnitudes and orientation agreement $c \in [-1,1]$ the squared magnitude is $\|\nabla F\|^2 = w^2 g_{\mathrm{ir}}^2 + (1-w)^2 g_{\mathrm{vi}}^2 + 2w(1-w) g_{\mathrm{ir}} g_{\mathrm{vi}} c$, whose minimum over $w \in [0,1]$ is $\dfrac{g_{\mathrm{ir}}^2 g_{\mathrm{vi}}^2 (1-c^2)}{g_{\mathrm{ir}}^2 + g_{\mathrm{vi}}^2 - 2 g_{\mathrm{ir}} g_{\mathrm{vi}} c}$ when the interior minimiser is attainable; the anti-parallel equal-magnitude case is its zero limit, and even orthogonal equal-magnitude gradients ($c = 0$) lose half their energy under an equal blend. The prior $\kappa$ of Section~\ref{sec:methods:cga} is defined over the full range of $c$ for that reason. A pointwise image-space weighting therefore cannot preserve a conflicting boundary; it can only choose how much to cancel (Fig.~\ref{fig:soft-vs-hard}). Whether the same conclusion extends to \emph{feature-space} fusion is a separate question and is treated here as a hypothesis rather than a result, since a fusion network applies nonlinear mappings and decoding after any feature-space weighting, so its output is not a convex combination of the inputs; the feature-space arm of Section~\ref{sec:methods:design} is the empirical test of that extension.""")

add('The natural alternative --- giving the operator more capacity',
    r"""The natural alternative --- giving the operator more capacity to represent boundaries --- we tested directly: a same-budget ablation degraded the structural metrics on the seed it was run on, but a two-seed repetition meets the same criterion in the opposite direction on one of them (verdict in Section~\ref{sec:exp}). Under this parameterization the capacity-dilution account is consequently neither transferred to nor excluded from structural gains, and the alternative we test next is argued on design grounds rather than on this arm.""")

add('These observations induce three design requirements',
    r"""These observations induce three design requirements. (R1)~\emph{Image-space operation}: which modality to keep is observable in image space, the state-dynamics arm supplies no replicated evidence that a feature-space intervention transfers, and image-space operation leaves the backbone untouched. (R2)~\emph{Conflict-triggered selectivity}: the mechanism should act only where the modalities conflict, so non-conflict pixels retain the pretrained behaviour and any measured difference is attributable to selection rather than to a global perturbation. (R3)~\emph{Per-pixel commitment behind a zero-initialized gate}: at a conflict pixel the output should move toward the locally salient modality rather than a blend of both, and the mechanism must start as an exact identity so that pretrained weights remain valid. (R2) is the requirement this paper ends up testing rather than relying on: the controls of Section~\ref{sec:exp:controls} do not support it, and we report that failure separately instead of restating the requirement as an accomplishment. (R1) and (R3) hold as stated.""")

# --------------------------------------------------------------- §3.2
# NOT compressed here. The conflict-signal block of §3.2 carries four numbered
# equations inside one blank-line-delimited chunk, so a paragraph-level
# replacement would delete them; that is what the environment-count guard below
# caught (equations 8 -> 5). §3.2's prose is left at its pre-pass length and its
# equations are untouched.

add('\\paragraph{Gate and combination.} A single scalar',
    r"""\paragraph{Gate and combination.} A single scalar $\alpha$, zero-initialized, bounds the mechanism globally; the learned conflict map localizes it:
\begin{equation}\label{eq:gate}
w = \tanh(\alpha)\cdot M, \qquad F = Y + w \odot (K - Y),
\end{equation}
equivalently $F = (1-w) \odot Y + w \odot K$ with a per-pixel, \emph{signed} $w \in [-\tanh|\alpha|, +\tanh|\alpha|]$. The sign matters: since $M \ge 0$, a negative $\alpha$ makes $w \le 0$ and $F$ moves \emph{away from} $K$, so the convex reading with $w \ge 0$ holds only for $\alpha \ge 0$ and is used below only in that case. In every checkpoint reported here $\alpha$ is positive and the gate is open --- $\alpha = +4.665$, $+3.674$ and $+3.749$ for seeds 42, 123 and 3407, i.e.\ $\tanh(\alpha) = 0.99982$, $0.99871$ and $0.99889$, with last-epoch values $+4.767$, $+4.551$, $+4.638$ --- so the sign is positive throughout, while the general signed form is retained because the objective does not constrain it. Where $M \to 0$ the output equals $Y$ exactly; where the mechanism acts it moves toward the source mixture by at most $|\tanh(\alpha)|$. At initialization $\tanh(0) = 0$, hence $F \equiv Y$ at every pixel.""")

# --------------------------------------------------------------- §3.3
add('Two disclosures about this recipe',
    r"""Two disclosures about this recipe are load-bearing for how every number in Section~\ref{sec:exp} should be read. First, the arm is a \emph{bundle}: module, conflict-grounding loss, commit-weighted loss, a separate high learning rate for the module, a schedule extended from 20 to 32 epochs and a best-validation checkpoint rule are introduced together, and no reported comparison separates them. Closing that gap requires an orthogonal-factor ablation under one budget and one checkpoint rule; that ablation was \textbf{not run}, because the gate authorizing it --- replication of the primary endpoint under a cluster-aware analysis --- was not met (Section~\ref{sec:exp:verdicts}). The consequence is accepted rather than argued away: the reported CGA$-$B0 deltas are the effect of the \emph{recipe as a whole}, and this paper does not claim to have identified the \emph{operator} as their cause. The pre-freeze implementation is labelled \texttt{CGA-v1} wherever that distinction matters. Second, the training run is \emph{not} numerically stable: late-epoch validation NaN appears in all three CGA-line seeds while the baseline line, including the 32-epoch matched control, completes without NaN, so every reported CGA number comes from a best-validation checkpoint selected \emph{before} NaN onset (Section~\ref{sec:exp:negative}). The method is recorded as an unstable experimental prototype rather than a finished pipeline.""")

add('\\paragraph{Provenance of the pre-registered criterion.}',
    r"""\paragraph{Provenance of the pre-registered criterion.} The detection criterion was registered on 9 September 2026, whereas the seed-42 checkpoint behind the main table's CGA row was written on 25 August 2026 and the gate thresholds, the two base conventions and the wording rules were fixed on 13--15 September. The pre-registration is therefore a \textbf{later-stage prospective re-test with a staged lock}: it fixes the criterion and the reporting rules before the budget-matched re-test they govern, and does not retroactively cover the architecture, recipe or checkpoint that preceded it. Section~\ref{sec:exp:repro} gives the item-by-item timeline.""")

# --------------------------------------------------------------- §3.4
add('\\paragraph{Stricter gates and content controls.}',
    r"""\paragraph{Stricter gates and content controls.} Three stricter gates were fixed alongside the primary endpoint: gate-C1 requires the high-conflict recall difference to reach $+0.02$; gate-C2 requires the all-object mAP50 to improve by at least $+0.01$; gate-C3 requires SF and AG to be non-inferior within a relative margin of $-1\%$ against the same-budget baseline, with the boundary convention that the threshold is inclusive and the comparison is made on unrounded values, so a row displayed as exactly $-1.00\%$ has to be resolved from its unrounded value. Inference-time content controls complete the design: the learned map can be replaced at test time by an all-ones map or by a fixed seeded permutation of itself (density preserved, placement destroyed). These hooks are part of the module code, not post-hoc edits, and they modify the inference path only, so the controls are comparable to the method arm on the same weights.""")

# --------------------------------------------------------------- §3.5
add("CGA's learnable budget is confined to two small convolutional stacks",
    r"""CGA's learnable budget is two small convolutional stacks (16-channel hidden width) and one scalar; the Sobel operators are fixed, and the module is attached at a single point at output resolution, so its cost does not scale with backbone depth. Its footprint is selective rather than global: the applied weight is proportional to the conflict map, and at load time the module is an exact no-op. CGA adds $1{,}523$ parameters to the $3{,}562{,}981$-parameter backbone ($+0.043\%$), $2.5\%$ of single-image latency at $507\times507$ ($208.40\pm3.36$ against $203.37\pm1.70$~ms; against the official weights, $208.96\pm0.89$~ms, the difference lies inside the run-to-run spread) and $1.3\%$ at $1034\times769$ ($694.52\pm3.52$ against $685.87\pm1.81$~ms), and no measurable peak memory, since the peak is dominated by backbone activations. Table~\ref{tab:cost} gives the full profile. Both sizes are constrained by the architecture: the patch-embedding stage floors a division by six and the patch-merging stage needs an even feature map, so this implementation accepts only $d \in \{12m+1, 12m+2, 12m+3\}$ with $((d-4)//3+1)$ divisible by four --- which is why the frozen fusion metrics are computed at $507\times507$ (tiled) and generation feeds $1034\times769$ (native, replicate-padded). Neither $512^2$ nor native $1024\times768$ is runnable here, and padding costs $1.1\%$ extra pixels, cropped away before any metric is computed. Backbone FLOPs are not reported, since the profiler counts parameters, latency and peak memory and no FLOP-counting dependency is part of this release; the module's own multiply-accumulates are counted from the convolution output shapes and appear in Table~\ref{tab:cost}.""")

add('\\paragraph{Measurement settings.}',
    r"""\paragraph{Measurement settings.} The environment is stated in full because latency figures are only interpretable with it. All timings were taken on a single NVIDIA GeForce RTX 3050 Laptop GPU (4\,GB) under driver 592.27, PyTorch 2.1.0 with its bundled CUDA 11.8 runtime and cuDNN 8.7.0 (\texttt{torch.backends.cudnn.version()} $= 8700$), GPU otherwise idle. Table~\ref{tab:cost} times a block of thirty passes per repeat at \emph{fp32} (no autocast) and reports the mean over three repeats. Because that cannot separate the per-pass distribution from the repeat-to-repeat spread, a second run timed each pass individually with the device synchronised before and after every pass (10 warm-up, $3\times30$ timed, $n = 90$ per cell), confirming the scale: $+2.08\%$ at P50 and $+2.09\%$ at P95 at $507\times507$, and $+1.20\%$ at P50 and $+2.50\%$ at P95 at $1034\times769$. The per-pass protocol carries synchronisation overhead and reports higher absolute levels (CGA $236.6$ against $208.4$~ms at $507\times507$); what is comparable across protocols is the ratio within one protocol.""")

# --------------------------------------------------------------- §4.1
add('All quantitative evidence in this paper is produced by a single evaluation',
    r"""All quantitative evidence is produced by a single evaluation harness, so every row of every table is comparable by construction. Fusion quality is measured on the full 300-image M3FD test split (TarDAL \cite{liu2022tardal}) by the unified evaluator \texttt{eval\_metrics.py} on the luminance channel, reporting six metrics: entropy (EN), spatial frequency (SF), average gradient (AG), mutual information (MI), QABF \cite{xydeas2000objective} and VIF \cite{sheikh2006image}. The same evaluator, channel convention and per-image CSV schema apply to all eight re-implemented baselines and to all three S4Fusion variants.""")

add('\\paragraph{Data composition and statistical units.}',
    r"""\paragraph{Data composition and statistical units.} The evaluation population is fixed and reported in full, because every count in this paper is a count over it. The split is the 300-image M3FD manifest (\texttt{dataset/manifests/m3fd\_test.csv}); after the source-pair and minimum-box filters of the object collector it yields $2{,}583$ annotated objects, of which $878$ fall in the high-conflict tercile, and those $878$ are spread over $181$ \emph{images} --- a mean of $4.85$ objects per image, maximum $13$. That nesting is why the detection endpoint is analysed at the image level: objects in one image share its fused output, its detector pass and its local registration. The detector-side environment is inherited from the DCEvo release and is \emph{not} pinned in this paper's artifacts; the fusion-side environment is pinned (\texttt{requirements-brss.txt}, torch 2.1.0+cu118).""")

add('Statistical testing follows the protocol: per-image paired',
    r"""Statistical testing follows the protocol: per-image paired Wilcoxon with Holm correction within each family, image-clustered bootstrap and permutation tests as the confirmatory layer for the detection endpoints, and exact binomial (McNemar-style) tests on recovered/lost objects retained as a sensitivity analysis. All hypotheses, endpoints and thresholds were fixed before the corresponding experiments; where a test fails to reject the text says that no difference was detected rather than that the arms are equivalent.""")

# --------------------------------------------------------------- §4.2
add('Three readings of Table~\\ref{tab:main} matter',
    r"""Three readings of Table~\ref{tab:main} matter. First, the QABF difference has to be quoted with both the baseline \emph{and} the aggregation level, because matching the levels changes the picture: against the 20-epoch retrain (B0) the seed-42 comparison ($n = 300$, one trained model each side) gives $+0.0155$ ($p = 7.1\times10^{-49}$, $r_{\mathrm{rb}} = +0.98$), while the same convention pooled over three seeds gives $+0.0113$ (95\% CI $[+0.0108, +0.0118]$); against the budget-matched 32-epoch retrain (B0\_e32) the pooled comparison gives $\mathbf{+0.0061}$ (95\% CI $[+0.0056, +0.0066]$). The correct same-level statement about the schedule is therefore $+0.0113$ against $+0.0061$, roughly $1.9\times$, not the $2.5\times$ a single-seed figure against a pooled one would suggest. The comparison against the official weights ($+0.0302$) is context only, since it bundles the retrain's own gain. Second, CGA's VIF is within $-0.0006$ of the official weights and a paired Wilcoxon rejects no difference ($p = 0.5571$); that is not the same as showing equivalence. Third, no single method dominates all six metrics --- EMMA leads SF and AG, Diff-IF leads MI, MetaFusion leads EN --- and no claim is made that the S4Fusion family is the best fusion model overall. Since the CGA arm follows the registered 32-epoch schedule, the CGA$-$B0 deltas should be read as the effect of the recipe rather than of the gate operator alone. The closest conflict-aware methods of Section~\ref{sec:related} are not rows of this table; they are compared on mechanism axes (Table~\ref{tab:positioning}). Figure~\ref{fig:qualitative} complements the table with two scenes against the sources, the official weights, the B0 retrain and three re-implemented baselines.""")

# --------------------------------------------------------------- §4.3
add('Two features of Table~\\ref{tab:perseed} matter',
    r"""Two features of Table~\ref{tab:perseed} matter more than the aggregate. First, the \emph{sign} is stable in all three seeds except SF, which is negative on two and statistically null on the third ($+0.0038$, $p_{\mathrm{Holm}} = 0.20$) --- so the honest statement is not ``SF degrades on 3/3 seeds'' under the matched convention. Second, the \emph{magnitude} is not stable: the matched QABF difference ranges over a factor of three across seeds, and the matched SF cost over a factor of twenty-three once s3407 is included. A direction that replicates while the magnitude moves by a factor of three is a real but weakly identified effect, which is why no single pooled magnitude is attached to a per-seed claim.""")

add('Read together, the two tables say the following',
    r"""Read together, the two tables say this: the information- and fidelity-oriented metrics improve in all three seeds individually under the matched convention, the structural sharpness metrics degrade except that SF is not distinguished from zero on s3407, and no per-seed magnitude may be quoted without its seed. Seed-level tests over $n = 3$ are intentionally omitted, since the minimum attainable Wilcoxon $p$ with three values is 0.25 --- precisely why replication is counted per seed and never inferred from a pooled statistic.""")

# --------------------------------------------------------------- §4.4
add('Why the H1 verdict is unstable',
    r"""The arm is meant to modulate the scan with a \emph{boundary-reliability} estimate, so the protocol carries the control analogous to CGA's: the estimator's output is replaced at inference time by a uniform map and, separately, by a fixed seeded permutation of itself. Neither replacement changes the fused output materially (against the modulated arm, SF moves by $+0.0002$ and $+0.0001$ and AG by $+0.0000$, $p = 0.24$ and $0.60$), and against B0 both reproduce the seed-42 degradation in full (SF $-0.0188$ and $-0.0190$, AG $-0.0126$, QABF $-0.0005$). The effect is therefore not a property of boundary reliability at all: a constant field, carrying no information about the image, and a permuted one, carrying the right values in the wrong places, both produce it. That is the same pattern the CGA controls report (Section~\ref{sec:exp:controls}), and it explains why the H1 verdict changes sign with the seed --- what varies is a global, content-independent change to the scan gains, not a boundary-driven allocation of capacity. We accordingly read this arm as a verdict on the state-capacity account in neither direction.""")

add('The two conventions agree in direction and disagree in verdict',
    r"""The two conventions agree in direction and disagree in verdict: every seed's object-level delta is positive under both, but the criterion is met on three seeds under the single-baseline convention and on one under the matched one, and the cluster-aware test agrees with that one. We state plainly what that means: \emph{the primary criterion does not replicate}. The pooled across-seed count and the Fisher combination appear only because the protocol requires them, and both are descriptive --- $42$ recovered against $18$ lost ($p = 2.67\times10^{-3}$) and $p = 2.02\times10^{-2}$ respectively. Neither is independent evidence, since the three seeds are evaluated on the same $181$ images with the same detector and ground truth, and neither substitutes for the per-seed count. The identical s123/s3407 rows of the single-baseline table are an artifact of sharing one baseline: against their own 32-epoch baselines those two seeds give $13/7$ and $11/7$, and reading the matched convention as three independent readings or the single-baseline one as two leaves one passing reading (s42 alone) either way.""")

add('The identical s123/s3407 rows in the single-baseline convention', '')
add('Every seed shows a positive object-level delta', '')

add('\\paragraph{Two finer statistics for the detector endpoint.}',
    r"""\paragraph{Two finer statistics for the detector endpoint.} Two finer checks were run afterwards and are reported because they cut in different directions. First, per-image AP is computable offline from the stored predictions, so the mAP50 difference can be given a distribution: under the single-baseline convention a bootstrap over images ($B=2000$, fixed seed) puts the difference at $+0.0161$ with a $95\%$ interval of $[+0.0065,+0.0270]$, which excludes zero but also does not exclude values below the registered $+0.01$ gate, so gate-C2 is not unambiguously met; under the matched convention the same statistic gives $+0.0114$, $+0.0062$ and $+0.0083$, all below the gate. The statistic is not the evaluator's mAP50 --- it averages per-image AP over images, whereas the evaluator averages per-class AP with 101-point interpolation, which is why the levels differ ($0.8048$ and $0.7887$ here against $0.7282$ and $0.7197$ there) --- and both are reported side by side rather than reconciled. Second, the all-object check removes the registration-defined conflict filter: across all $2583$ objects CGA recovers $44$ that the baseline misses and loses $13$ (exact binomial $p = 4.7\times10^{-5}$; recall $0.6384$ against $0.6264$), which directly addresses the selection-bias objection since the high-conflict subset is defined by the same quantity that triggers the mechanism and this difference is not confined to it. Both checks are object-level, so the within-image dependence Table~\ref{tab:cluster} models applies to them too, and both are reported as sensitivity rather than confirmatory.""")

# --------------------------------------------------------------- §4.5
add('\\paragraph{The trained selector is effectively binary',
    r"""\paragraph{The trained selector is effectively binary, and its support is sparse.} The source-selection weight $s$ is continuous by construction, so whether the trained selector behaves like a binary choice is an empirical question about the weights rather than a property of the formula --- which is why the paper calls the mechanism a continuous residual arbitration and reserves \emph{trained near-binary selector} for the measured behaviour. On the seed-42 checkpoint the selector saturates almost everywhere: $P(s \notin [0.1, 0.9]) = 0.9560$, with $P(s \le 0.1) = 0.784$ and $P(s \ge 0.9) = 0.172$. Hardness $\min(s, 1-s)$ falls to $0.0139$ over all pixels and $0.0056$ where the mechanism acts, against $0.1192$ at initialization --- a $20$--$30\times$ sharpening that is what the term \emph{near-binary} rests on. Three further properties are reported with it. The selection is strongly asymmetric, leaning toward the visible source. The support is sparse: $\overline{M} = 0.0447$ and $P(M > 0.5) = 0.33\%$ of pixels. And the learned map departs from the prior it is supervised against: the per-image Spearman correlation between $M$ and $\hat\kappa$ averages $0.4487$, so the map is related to the prior but is not a copy of it. Table~\ref{tab:selector} repeats the measurement on the other two seeds and separates the three quantities the discussion relies on --- how binary the selection is, how dense its support is, and how far the learned map follows the prior; all three move within a narrow band across seeds (saturation $0.935$--$0.956$, hardness $0.0139$--$0.0205$, $\overline{M}$ $0.0301$--$0.0447$, $\rho$ $0.365$--$0.449$), so the near-binary, sparse, prior-related character is a property of the recipe rather than of the seed that carries the headline row.""")

add('At the pixel level, the intervention is selective rather than global',
    r"""At the pixel level the intervention is selective rather than global, and the signature is one of \emph{sparsity} rather than of conflict-correctness. On the six highest learned-conflict samples the mean absolute CGA$-$B0 difference is 0.0125--0.0170 while the per-sample difference-map peaks are 0.5940, 0.5902, 0.5831, 0.5675, 0.6097 and 0.4253, read from the archived arrays. A small mean with a large peak means most of the image is untouched while a small set of pixels is strongly re-assigned; it does not show that those pixels are the conflicting ones, and the control of Section~\ref{sec:exp:controls} tests exactly that and returns a negative. Figures~\ref{fig:panel-a} and~\ref{fig:panel-b} show two panels, each with five columns: the infrared source, the visible luminance, the closed-form conflict prior $\hat\kappa$ (per-image max-normalized, input-derived, no annotation --- the panel labels it ``conflict target''), the learned support map $M$, and the absolute CGA$-$B0 difference map.""")

# --------------------------------------------------------------- §4.6
add('The three-seed picture is less favourable',
    r"""The three-seed picture is less favourable than the single-seed one and is reported as it is. The two metrics that should improve if the mechanism preserved chrominance behave differently: CIEDE2000 colour difference against the visible reference decreases on all three seeds and significantly on two, a consistent improvement, whereas EOR --- the RGB-space edge-orientation agreement with the sources --- is positive on all three seeds but significant on none ($p = 0.065$, $0.96$, $0.23$, intervals all including zero), so the earlier single-seed reading of this metric as a significant improvement does not survive either the matched baseline or the replication and is withdrawn. The two descriptive quantities, RGB three-channel SSIM and Colorfulness, degrade on all three seeds with significance and track the structural cost seen in the luminance metrics, while ECS and OBR flip sign between seeds and are not interpretable at this sample size. The honest summary is a consistent, mostly significant reduction of colour distance to the visible reference; a consistent, uniformly non-significant edge-orientation change; and a consistent, significant degradation of the two fidelity descriptors, which is the chrominance-side echo of the same structural trade-off rather than a new failure mode.""")

add('Two provenance notes belong with this table',
    r"""Two provenance notes belong with this table. The audit is reported at the matched convention because that is the convention the rest of the paper follows; the single-seed figures of the previous version were computed against the 20-epoch shared baseline and are superseded. And the RGB reconstruction path is a separate implementation from the luminance evaluator, so the levels are comparable only within the table --- SF, AG, ECS, RGB SSIM, CIEDE2000 and Colorfulness reproduce the frozen seed-42 values from that path exactly, while EOR and OBR differ from the frozen single-seed table by less than $10^{-2}$ in absolute terms because those two are the metrics the RGB path feeds.""")

# --------------------------------------------------------------- §4.7
add('\\paragraph{H1 --- the falsification does not replicate',
    r"""\paragraph{H1 --- the falsification does not replicate (already reported in Section~\ref{sec:exp:verdicts}).} The feature-space $B/C/\Delta$ arm degrades every structural metric on seed 42 (SF $-0.0190$, AG $-0.0126$, QABF $-0.0005$; Holm $p \leq 5.63\times10^{-27}$) but inverts the criterion on seed 123 (SF $+0.0328$, AG $+0.0172$) and leaves seed 3407 with AG alone, with QABF's median down by $0.0005$ on all three. It is reported as a negative result about the \emph{arm}, and as a second instance of the pattern running through this paper: a single-seed verdict in this pipeline does not survive repetition. The arm's own control closes the question of what produced it --- a constant reliability field and a permuted one each reproduce the seed-42 degradation in full --- so the effect is a content-free global change to the scan gains rather than a boundary-driven one, and the ``mechanism-inside-the-SSM'' narrative is retired as unproven rather than refuted.""")

add('\\paragraph{Distillation --- deterministic failure',
    r"""\paragraph{Distillation --- deterministic failure, reported as a negative result.} The reliability-map distillation arm (teacher = trained CGA seed-42 model with depths 1,2,1; student depths 1,1,1 with \texttt{-{}-use-cga}; output-L1 1.0, feature SmoothL1 0.2, boundary-KL 0.5; 20 epochs, crop 128, seed 42) produced NaN validation loss in epoch 1 and NaN train \emph{and} val losses for epochs 2 through 20; no best checkpoint was ever saved, leaving only an unusable NaN-weights \texttt{\_last.pt}. Per the pre-registration discipline we did not tune hyperparameters and did not rerun, and the component is reported as a first-attempt failure rather than a supported contribution. Two candidate explanations are on record --- the commitment loss diverging in this configuration, possibly the same phenomenon as the late-training NaNs, and an implementation issue in the boundary-KL path on a shallow student --- and neither is tested here.""")

add('That decision has a consequence which we state',
    r"""That decision has a consequence we state rather than leave implied. Two experiments that would have strengthened the attribution were deliberately \emph{not} run, for the same reason in both cases: the evidence they would be interpreted against did not clear its own gate. A \emph{stable retraining} of the CGA arm would have established whether the effect survives a numerically sound run, and an \emph{orthogonal-factor ablation} --- module only, plus conflict loss, plus commit loss, plus module learning rate, plus extended schedule, all under one budget and one checkpoint rule --- would have isolated which ingredient produces it. Neither was run, because the primary endpoint for this arm is a seed-specific, non-replicated effect (Table~\ref{tab:cluster}); attributing a non-replicating effect to a specific factor would not have changed that finding. The consequence is accepted openly: the method is reported as an \emph{unstable experimental prototype}, the recipe as a bundle, and this paper does not claim to have identified the mechanism of the difference it measures.""")

# --------------------------------------------------------------- §4.8
add('At the fusion end, per-image paired comparisons',
    r"""At the fusion end, per-image paired comparisons against the learned map (300-image M3FD test; five of six metrics, since VIF is not recorded by the evaluator build that produced these runs) show the same split: the all-ones map sits above the learned one on the structural and information metrics (SF by $+2.00$, AG by $+0.35$, MI by $+2.79$, Holm-corrected $p \leq 2.3\times10^{-22}$), with EN slightly lower and QABF not distinguished from it ($-0.0012$, $p = 0.35$); the shuffled map moves every metric by at most $0.44$.""")

add('The uniform control is \\emph{not} a second negative',
    r"""The uniform control is \emph{not} a second negative and not a free variant either; it is a different operating point, and summarising it as ``commitment everywhere does at least as well'' would misreport it in both directions. Committing everywhere raises high-conflict recall substantially and lowers all-object mAP50 below both the learned and the shuffled arm while increasing false positives per image and reducing all-object precision: it buys recall by giving up ranking quality and precision, which is exactly the exchange a deployment decision would have to price. Nor is the recall side as strong as its object-level $p$-value suggests: with the image as the unit the uniform arm is $21$ images up against $24$ down over the $181$ images carrying the subset ($p = 0.77$), and only the exact sign-flip test on the image scores is marginal ($p = 0.0495$); the $1.1\times10^{-5}$ figure is the object-level sensitivity statistic, inflated by counting roughly five objects per image as independent. What the uniform arm establishes is therefore the \emph{operator}: image-space per-pixel selection moves gradient-energy, information and detection quantities whether or not it is confined to conflict pixels. What it does not establish is that the operator is a uniform improvement, and the paper does not claim it is. Two caveats are stated rather than buried: the fusion end carries five of six metrics, and the detection end rests on a single detector; neither affects the direction, which is the same at both endpoints.""")

add('The rules are defined as follows',
    r"""The rules are defined so that the table can be read without the code. \emph{max} sets the selection weight to $1$ on the modality with the larger local intensity and $0$ on the other; \emph{gradient} does the same by Sobel magnitude, the hard version of the rule the untrained selector already implements. \emph{Global} applies the rule at every pixel, \emph{conflict only} only inside the fixed p85 edge mask used by the earlier exploratory control, and the unqualified rows only inside the mechanism's own learned support $M > 0.5$, which covers $0.33\%$ of pixels. Every arm keeps CGA's architecture, gate and support and changes only the selector, and the two support levels are cross-validated against the same rules, so the influence of the \emph{support} can be separated from that of the \emph{rule}.""")

add('Four parameter-free rules applied through the fixed heuristic mask',
    r"""Four rules applied through the fixed mask are significantly worse than CGA, the two conflict-confined ones by $0.049$ and $0.156$ recall. Replacing the mask with CGA's own support does not rescue them: hard max and hard gradient inside $M > 0.5$ remain worse than CGA by $0.018$ and $0.022$ ($p = 1.5\times10^{-3}$ and $3.1\times10^{-4}$) and are not distinguished from the same-budget baseline. The sharpest arm is \emph{oracle-init}: CGA's architecture, support and gate unchanged, with only the selector reset to its zero-initialized value. It is worse than CGA by $0.0251$ ($p = 2.7\times10^{-5}$) and slightly below doing nothing at all. What training the selector buys is therefore the difference between a difference and none, in this seed --- and the qualification matters, since every arm here is measured on the seed-42 checkpoint against the shared 20-epoch baseline, i.e.\ against the effect Table~\ref{tab:cluster} finds on that same seed. Table~\ref{tab:free} therefore supports a statement about the \emph{operator} at that operating point and inherits the non-replication recorded above; what it establishes, within that scope, is that the conclusion about the \emph{trigger} does not extend to the \emph{selection}.""")

# --------------------------------------------------------------- §4.9
add('The claim made here is deliberately narrower',
    r"""The claim made here is deliberately narrower than ``every number can be regenerated''. What the released artifacts support is that every \emph{statistic} can be recomputed from the released per-image and per-object intermediate results without retraining; that the fusion-side pipeline can be re-run end to end from the pinned environment; and that the detection endpoint can be recomputed from the released fused images and predictions, but not guaranteed to reproduce bit-exactly, because the detector library stack is inherited from the DCEvo release and is not pinned in the artifacts accompanying this paper. We state it that way because it is what is true, and the detector environment is recorded as the weakest link rather than left implicit.""")

add('The honest summary of Table~\\ref{tab:timeline}',
    r"""The honest summary of Table~\ref{tab:timeline} is that the \emph{criterion and reporting rules} for the arbitration re-test were fixed before that re-test was run, while the \emph{architecture, training recipe, seed-42 checkpoint and choice of testbed} all pre-date them. The study is a later-stage prospective re-test with a staged lock, not a full pre-registration, and the word is not used here to describe anything larger.""")

add('A reproducibility property specific to this design',
    r"""One property of the design deserves emphasis: because the gate is zero-initialized, the trained model can be loaded side-by-side with the official S4Fusion weights, and setting the gate to zero recovers the baseline output exactly ($\tanh(0) = 0$). Any user of the released code can verify that the unmodified official weights are reproduced bit-exactly by the augmented model with the gate closed, and that the reported differences come only from opening it.""")

# --------------------------------------------------------------- §5
add('This section reads the evidence in three registers',
    r"""This section reads the evidence in three registers: what it supports, what it does not, and where the method sits.""")

add('The question of this study was narrow by design',
    r"""The question of this study was narrow by design: at pixels where the modalities disagree, does an explicit image-space per-pixel commitment toward the locally salient modality recover what a pointwise blend loses? Four observations support an answer at the level of mechanism, each attached to the quantity it is about.""")

add('The fusion-metric profile is coherent with that reading',
    r"""The fusion-metric profile is coherent with that reading, within the same scope. Per-seed matched differences (Table~\ref{tab:perseed}) are positive for MI, QABF, VIF and EN in all three seeds and negative for AG in all three, with SF negative on two and undecided on the third. One nuance deserves an explicit reading: relative to the official weights the B0 retrain itself loses MI while gaining QABF, and CGA recovers most of that MI loss on top of B0, so the CGA$-$B0 MI difference is partly a recovery of the retrain's own cost rather than a gain over the official model. Because the evaluator's MI is the sum of its two directed components, the difference decomposes into an infrared-side and a visible-side component ($1.104 \to 1.253$ and $2.104 \to 2.681$), so neither falls and the visible side moves the more of the two --- consistent with the selection asymmetry in Table~\ref{tab:selector} and weighing against the simplest reading, that the difference is only a redistribution of weight between sources, without excluding it. The multi-resolution measurement points the same way (Section~\ref{sec:exp:vis}) but belongs to the seed-42 arm; read together these are mechanism-level observations on one testbed, and the paper does not promote them to an effect-size claim.""")

add('The reliability-map distillation arm is a negative result ---',
    r"""The reliability-map distillation arm is a negative result --- validation NaN from the first epoch, no best checkpoint ever saved --- reported as a failure record, not rehabilitated (Section~\ref{sec:exp:negative}).""")

add('The comparison with the closest conflict-aware methods',
    r"""The comparison with the closest conflict-aware methods is defined on mechanism axes, not on gain magnitude, and at the granularity Table~\ref{tab:positioning} records. ARC3Fusion \cite{tian2026adaptive} coordinates consensus--complementarity--conflict in feature space through per-position three-branch Softmax weights, and GatedFusion-Net \cite{brenner2026gatedfusion} learns per-pixel Sigmoid confidence masks; both are continuous, feature-space, soft coordinators. CGA differs on operating space and on the discreteness of the final output: it operates on the two registered source images and its selection sharpens to a near-binary decision after training, but its output is a continuous residual arbitration rather than a discrete pick, so the honest contrast is ``image-space with a trained near-binary selector'' against ``feature-space with a soft weight'', not hard against soft. The trigger axis is no longer part of the claim at all, since Section~\ref{sec:exp:controls} removes it. What survives is the axis distinction, and it is independent of the gain magnitude: a small, non-replicating effect weakens the practical-value claim, not the axis distinction.""")

add('The commitment philosophy itself has a long lineage',
    r"""The commitment philosophy has a long lineage. The classical select/choose rules \cite{burt1993enhanced,zhang1999categorization,piella2003general} formalized choosing the salient source where sources disagree, and the learning-based multi-focus decision-map line \cite{ma2021endtoend} still makes per-pixel binary choices, but driven by defocus within same-modality pairs. CGA inherits the commitment idea and moves it to cross-modal conflict: the trigger is inter-modal gradient conflict, the selection is learned end-to-end, and it is applied through a zero-initialized gate; the measurement of Section~\ref{sec:exp:vis} then shows that the \emph{learned} part, not the trigger, is what the operator's behaviour rests on.""")

add('Finally, the positioning is deliberately that of a single-testbed',
    r"""Finally, the positioning is deliberately that of a single-testbed mechanism audit --- the frame the title carries --- not a comprehensive or class-level superiority claim. EMMA leads SF and AG and Diff-IF leads MI; CGA's leading metric is QABF, with VIF not distinguished from the official weights. S4Fusion is the testbed because its public weights make the comparison controlled, not because it is assumed to be the strongest or most representative backbone, and the conclusions are scoped to S4Fusion, M3FD and the single fixed detector throughout.""")

# --------------------------------------------------------------- Conclusion
add('This study set out to locate the residual failure',
    r"""This study set out to locate the residual failure of a scan-and-blend selective state-space fusion backbone at modal boundaries, on one testbed. The first arm did not settle the question: feature-space modulation of the state dynamics degrades the structural metrics on one seed under a same-budget protocol, meets the same criterion in the opposite direction on a second, and lowers QABF's median on all three, and the arm's own control shows why the sign moves --- a constant reliability map and a permuted one each reproduce the seed-42 degradation in full. The arm tested next intervenes at conflicting pixels instead, on the design argument rather than on that verdict.""")

add('Two extensions that would have widened the claim',
    r"""Two extensions that would have widened the claim --- a factor-resolved ablation of the training recipe, and an external-validity programme on a second dataset, a second detector and controlled misregistration --- were not run, because the gate that authorizes further performance work did not open; their absence is why this paper measures a recipe rather than an operator, and why it is scoped to one test bed. Two properties of the pipeline bound what any individual number means: the baseline had not converged at the matched budget, and two runs of one arm with one seed do not reproduce each other to better than a few thousandths of validation loss. Within these boundaries what remains is a mechanism that is implemented and active but not a reliable source of gain, a set of negative results that are legible because the protocol made them so, and a protocol --- criterion layering, both base conventions reported as non-comparable, controls at both endpoints, cluster-aware inference, replication counted per seed --- that is the part of this work most directly reusable.""")

add('Whether spatially regularized selection fields',
    r"""Whether spatially regularized selection fields, a stabilized training recipe, factor-resolved attribution or cross-dataset validation make the mechanism reliable remains open; they are questions, not promises, and the negative results above are why.""")

# ------------------------------------------------------------------ apply
t = open(MAIN, encoding='utf-8').read()
before = {env: t.count('\\begin{' + env + '}')
          for env in ('figure', 'figure*', 'table', 'table*', 'tabular',
                      'enumerate', 'itemize', 'equation', 'align')}
paras = t.split('\n\n')
import re as _re

_BANNER = _re.compile(r'^\s*(?:%.*?\n\s*)+')


def _clean(p):
    return ' '.join(_BANNER.sub('', p).split())


norm = [_clean(p) for p in paras]

problems = []
for anchor, new in R:
    a = ' '.join(anchor.split())
    hits = [i for i, p in enumerate(norm) if a in p]
    if len(hits) != 1:
        problems.append((a, len(hits)))
if problems:
    for a, n in problems:
        print(f'  {n} match(es): {a[:80]!r}')
    raise SystemExit(f'{len(problems)} anchor(s) failed; nothing written')

for anchor, new in R:
    a = ' '.join(anchor.split())
    hits = [i for i, p in enumerate(norm) if a in p]
    paras[hits[0]] = new

out = [p for p in paras if p.strip()]
new_t = '\n\n'.join(out)
after = {env: new_t.count('\\begin{' + env + '}') for env in before}
bad = {k: (before[k], after[k]) for k in before if before[k] != after[k]}
if bad:
    for k, (b, a) in bad.items():
        print(f'  ENV COUNT CHANGED {k}: {b} -> {a}')
    raise SystemExit('environment counts changed; nothing written')

open(MAIN, 'w', encoding='utf-8', newline='\n').write(new_t)
print(f'main.tex: {len(R)} content-anchored replacements applied, '
      f'all anchors unique, all environment counts preserved')
