import argparse
import re
import random
from dataclasses import dataclass
from io import BytesIO
from pathlib import Path

import torch
import torch.nn.functional as F
from PIL import Image
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms


IMG_EXTS = {".png", ".jpg", ".jpeg", ".bmp", ".tif", ".tiff"}
EPS = 1e-12


def _resolve_device(device_arg: str) -> torch.device:
    if device_arg == "auto":
        return torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    return torch.device(device_arg)


def _parse_crop_size(value: str):
    if "x" in value:
        parts = value.lower().split("x")
    elif "," in value:
        parts = value.split(",")
    else:
        size = int(value)
        return (size, size)
    if len(parts) != 2:
        raise ValueError("crop_size must be like 256 or 256x256 or 256,256")
    return (int(parts[0]), int(parts[1]))


def _parse_scales(value: str):
    if value is None:
        return ()
    text = value.strip().lower()
    if text in {"", "none", "off", "null"}:
        return ()
    parts = [p.strip() for p in text.replace("x", ",").split(",") if p.strip()]
    return tuple(int(p) for p in parts)



def _valid_crop_dim(x: int) -> int:
    if x <= 4:
        return x
    # Ensure patch embed output size is divisible by 4 to avoid PatchMerging truncation.
    while x > 4:
        out = (x - 4) // 3 + 1
        if out % 4 == 0:
            return x
        x -= 1
    return x


def _adjust_crop_size(size):
    h, w = size
    return (_valid_crop_dim(h), _valid_crop_dim(w))


def rgb_to_y(rgb: torch.Tensor) -> torch.Tensor:
    r = rgb[0:1]
    g = rgb[1:2]
    b = rgb[2:3]
    y = 0.299 * r + 0.587 * g + 0.114 * b
    return y.clamp(0, 1)


def sobel_grad(x: torch.Tensor) -> torch.Tensor:
    kx = torch.tensor([[1, 0, -1], [2, 0, -2], [1, 0, -1]], dtype=x.dtype, device=x.device).view(1, 1, 3, 3)
    ky = torch.tensor([[1, 2, 1], [0, 0, 0], [-1, -2, -1]], dtype=x.dtype, device=x.device).view(1, 1, 3, 3)
    gx = F.conv2d(x, kx, padding=1)
    gy = F.conv2d(x, ky, padding=1)
    # Compute the magnitude in fp32: under AMP autocast gx/gy are fp16 and the
    # 1e-12 epsilon underflows to 0, so flat regions (gx=gy=0) give sqrt'(0)=0/0=NaN
    # in the backward. fp32 keeps the epsilon effective (0/sqrt(eps)=0).
    gx, gy = gx.float(), gy.float()
    return torch.sqrt(gx * gx + gy * gy + EPS)


def edge_aware_smooth_loss(fused: torch.Tensor, ir: torch.Tensor, vi: torch.Tensor, k: float = 10.0):
    # Suppress spurious high-frequency artifacts in flat regions, keep edges sharp.
    grad_ref = torch.max(sobel_grad(ir), sobel_grad(vi))
    weight = torch.exp(-k * grad_ref)
    dx = torch.abs(fused[:, :, :, 1:] - fused[:, :, :, :-1])
    dy = torch.abs(fused[:, :, 1:, :] - fused[:, :, :-1, :])
    wx = weight[:, :, :, 1:]
    wy = weight[:, :, 1:, :]
    return (wx * dx).mean() + (wy * dy).mean()


def scale_consistency_loss(
    fused_hr: torch.Tensor,
    fused_lr: torch.Tensor,
    edge_weight: float = 0.5,
) -> torch.Tensor:
    """Keep HR fusion structurally consistent with direct LR fusion."""
    if fused_hr.ndim != 4 or fused_lr.ndim != 4:
        raise ValueError("scale_consistency_loss expects BCHW tensors")
    down = F.interpolate(fused_hr, size=fused_lr.shape[-2:], mode="bilinear", align_corners=False)
    loss_intensity = F.l1_loss(down, fused_lr.detach())
    if edge_weight <= 0:
        return loss_intensity
    loss_edge = F.l1_loss(sobel_grad(down), sobel_grad(fused_lr.detach()))
    return loss_intensity + edge_weight * loss_edge


def fusion_loss(
    fused: torch.Tensor,
    ir: torch.Tensor,
    vi: torch.Tensor,
    w_intensity: float,
    w_grad: float,
    w_smooth: float = 0.0,
    smooth_k: float = 10.0,
):
    target_intensity = torch.max(ir, vi)
    loss_intensity = F.l1_loss(fused, target_intensity)
    grad_fused = sobel_grad(fused)
    grad_target = torch.max(sobel_grad(ir), sobel_grad(vi))
    loss_grad = F.l1_loss(grad_fused, grad_target)
    if w_smooth > 0:
        loss_smooth = edge_aware_smooth_loss(fused, ir, vi, k=smooth_k)
    else:
        loss_smooth = torch.zeros((), device=fused.device, dtype=fused.dtype)
    total = w_intensity * loss_intensity + w_grad * loss_grad + w_smooth * loss_smooth
    return total, loss_intensity, loss_grad, loss_smooth


@dataclass
class DatasetSpec:
    zip_path: Path
    ir_prefix: str
    vi_prefix: str


class ZipPairDataset(Dataset):
    def __init__(
        self,
        split_path: str,
        m3fd_zip: str,
        roadscene_zip: str,
        crop_size,
        default_dataset: str | None = None,
        use_y: bool = True,
        augment: bool = True,
    ) -> None:
        self.items = []
        # Split files may be generated by PowerShell or editors that emit a BOM.
        # Use utf-8-sig and strip any stray BOM defensively so archive paths stay valid.
        with open(split_path, "r", encoding="utf-8-sig") as f:
            for line in f:
                line = line.strip().lstrip("\ufeff")
                if not line:
                    continue
                parts = line.split()
                if len(parts) == 1:
                    if not default_dataset:
                        raise ValueError("split file has no dataset id; set --default-dataset")
                    ds, name = default_dataset, parts[0]
                else:
                    ds, name = parts[0].lower(), parts[1]
                self.items.append((ds, name))

        self.specs = {
            "m3fd": DatasetSpec(Path(m3fd_zip), "Ir/", "Vis/"),
            "roadscene": DatasetSpec(Path(roadscene_zip), "RoadScene-master/cropinfrared/", "RoadScene-master/crop_LR_visible/"),
        }
        for ds in {ds for ds, _ in self.items}:
            if ds not in self.specs:
                raise ValueError(f"unknown dataset id: {ds}")
            if not self.specs[ds].zip_path.is_file():
                raise FileNotFoundError(f"zip not found: {self.specs[ds].zip_path}")

        self.crop_size = crop_size
        self.use_y = use_y
        self.augment = augment
        self.totensor = transforms.ToTensor()
        self._zips = {}

    def __len__(self) -> int:
        return len(self.items)

    def _get_zip(self, ds: str):
        zf = self._zips.get(ds)
        if zf is None:
            import zipfile

            zf = zipfile.ZipFile(self.specs[ds].zip_path, "r")
            self._zips[ds] = zf
        return zf

    def _read_image(self, ds: str, prefix: str, name: str, mode: str):
        zf = self._get_zip(ds)
        with zf.open(prefix + name) as f:
            img = Image.open(BytesIO(f.read())).convert(mode)
        return img

    def _pad_to_min(self, x: torch.Tensor, h: int, w: int):
        _, cur_h, cur_w = x.shape
        pad_h = max(0, h - cur_h)
        pad_w = max(0, w - cur_w)
        if pad_h == 0 and pad_w == 0:
            return x
        return F.pad(x, (0, pad_w, 0, pad_h), mode="reflect")

    def _crop_pair(self, vi: torch.Tensor, ir: torch.Tensor, random_crop: bool):
        if self.crop_size is None:
            return vi, ir
        ch, cw = self.crop_size
        h = max(vi.shape[1], ir.shape[1], ch)
        w = max(vi.shape[2], ir.shape[2], cw)
        vi = self._pad_to_min(vi, h, w)
        ir = self._pad_to_min(ir, h, w)
        if random_crop:
            top = 0 if h == ch else random.randint(0, h - ch)
            left = 0 if w == cw else random.randint(0, w - cw)
        else:
            top = 0 if h == ch else (h - ch) // 2
            left = 0 if w == cw else (w - cw) // 2
        vi = vi[:, top : top + ch, left : left + cw]
        ir = ir[:, top : top + ch, left : left + cw]
        return vi, ir

    def __getitem__(self, idx: int):
        ds, name = self.items[idx]
        spec = self.specs[ds]
        ir_img = self._read_image(ds, spec.ir_prefix, name, "L")
        vi_img = self._read_image(ds, spec.vi_prefix, name, "RGB")
        ir = self.totensor(ir_img)
        vi_rgb = self.totensor(vi_img)
        vi = rgb_to_y(vi_rgb) if self.use_y else vi_rgb.mean(dim=0, keepdim=True)

        vi, ir = self._crop_pair(vi, ir, random_crop=self.augment)
        if self.augment:
            if random.random() < 0.5:
                vi = torch.flip(vi, dims=[2])
                ir = torch.flip(ir, dims=[2])
            if random.random() < 0.5:
                vi = torch.flip(vi, dims=[1])
                ir = torch.flip(ir, dims=[1])
        return vi, ir


def _set_seed(seed: int):
    random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def _trainable_params(model: torch.nn.Module, unfreeze_patterns, unfreeze_regex):
    params = []
    extra_params = []
    for name, p in model.named_parameters():
        match_extra = False
        if unfreeze_regex and unfreeze_regex.search(name):
            match_extra = True
        elif unfreeze_patterns:
            for pat in unfreeze_patterns:
                if pat and pat in name:
                    match_extra = True
                    break
        if "global_gates" in name or "dynamic_gate" in name:
            p.requires_grad = True
            params.append(p)
        elif match_extra:
            p.requires_grad = True
            extra_params.append(p)
        else:
            p.requires_grad = False
    return params, extra_params


def _gate_l2(model: torch.nn.Module):
    regs = []
    for name, p in model.named_parameters():
        if "global_gates" in name and p.requires_grad:
            regs.append(p.pow(2).mean())
    if not regs:
        return None
    return torch.stack(regs).mean()


def main():
    parser = argparse.ArgumentParser(description="Train global_gates only (multi-scale global branch).")
    parser.add_argument("--train-split", default="splits/train.txt")
    parser.add_argument("--val-split", default="splits/val.txt")
    parser.add_argument("--default-dataset", default=None, help="use when split has only filenames")
    parser.add_argument("--m3fd-zip", default="archive.zip")
    parser.add_argument("--roadscene-zip", default="RoadScene-master.zip")
    parser.add_argument("--crop-size", default="256", help="crop size, e.g. 256 or 256x256")
    parser.add_argument("--batch-size", type=int, default=8)
    parser.add_argument("--epochs", type=int, default=5)
    parser.add_argument("--lr", type=float, default=1e-3, help="learning rate for global_gates")
    parser.add_argument("--lr-unfreeze", type=float, default=1e-5, help="learning rate for extra unfrozen params")
    parser.add_argument("--unfreeze-patterns", default="", help="comma-separated substrings to unfreeze (in addition to global_gates)")
    parser.add_argument("--unfreeze-regex", default="", help="regex to match params to unfreeze (in addition to global_gates)")
    parser.add_argument(
        "--allow-no-gates",
        action="store_true",
        help="allow training when no global_gates are present (e.g., baseline full fine-tune with fusion/ss2d scales=none)",
    )
    parser.add_argument("--num-workers", type=int, default=4)
    parser.add_argument("--device", default="auto")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--w-intensity", type=float, default=1.0)
    parser.add_argument("--w-grad", type=float, default=10.0)
    parser.add_argument("--w-smooth", type=float, default=0.0, help="edge-aware smoothness weight")
    parser.add_argument("--smooth-k", type=float, default=10.0, help="edge-awareness factor for smoothness loss")
    parser.add_argument("--w-gate", type=float, default=1e-3, help="L2 penalty on global gates")
    parser.add_argument("--w-scale", type=float, default=0.0, help="scale-consistency loss weight")
    parser.add_argument("--scale-edge-weight", type=float, default=0.5, help="edge term weight inside scale-consistency loss")
    parser.add_argument("--scale-ratio", type=float, default=0.5, help="LR branch size ratio for scale-consistency loss")
    parser.add_argument("--checkpoint", default="model/model.pkl")
    parser.add_argument("--save-path", default="model/model_ms_global_gateonly.pkl")
    parser.add_argument("--save-every", type=int, default=0)
    parser.add_argument("--ss2d-scales", default="none", help="comma-separated scales for SS2D global branch, or 'none'")
    parser.add_argument("--fusion-scales", default="4,8", help="comma-separated scales for FusionBlock global branch, or 'none'")
    parser.add_argument("--gate-type", default="scalar", choices=["scalar", "dynamic"], help="CSSC gate type")
    parser.add_argument("--dynamic-gate-hidden", type=int, default=32, help="hidden size for dynamic CSSC gate")
    args = parser.parse_args()

    _set_seed(args.seed)
    device = _resolve_device(args.device)
    crop_size = _parse_crop_size(args.crop_size)
    adj_crop_size = _adjust_crop_size(crop_size)
    if adj_crop_size != crop_size:
        print(f"Adjusted crop_size from {crop_size} to {adj_crop_size} to satisfy patch/fold constraints.", flush=True)
        crop_size = adj_crop_size
    ss2d_scales = _parse_scales(args.ss2d_scales)
    fusion_scales = _parse_scales(args.fusion_scales)
    print(f"Using ss2d_scales={ss2d_scales}, fusion_scales={fusion_scales}", flush=True)

    train_ds = ZipPairDataset(
        split_path=args.train_split,
        m3fd_zip=args.m3fd_zip,
        roadscene_zip=args.roadscene_zip,
        crop_size=crop_size,
        default_dataset=args.default_dataset,
        use_y=True,
        augment=True,
    )
    val_ds = ZipPairDataset(
        split_path=args.val_split,
        m3fd_zip=args.m3fd_zip,
        roadscene_zip=args.roadscene_zip,
        crop_size=crop_size,
        default_dataset=args.default_dataset,
        use_y=True,
        augment=False,
    )

    train_loader = DataLoader(
        train_ds,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.num_workers,
        pin_memory=True,
        drop_last=True,
    )
    val_loader = DataLoader(
        val_ds,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=args.num_workers,
        pin_memory=True,
        drop_last=False,
    )

    from S4Fusion import MambaNet

    model = MambaNet(
        ss2d_global_scales=ss2d_scales,
        fusion_global_scales=fusion_scales,
        gate_type=args.gate_type,
        dynamic_gate_hidden=args.dynamic_gate_hidden,
    ).to(device)
    if args.checkpoint and Path(args.checkpoint).is_file():
        ckpt = torch.load(args.checkpoint, map_location=device)
        model.load_state_dict(ckpt.get("model", ckpt), strict=False)

    unfreeze_patterns = [p.strip() for p in args.unfreeze_patterns.split(",") if p.strip()]
    unfreeze_regex = re.compile(args.unfreeze_regex) if args.unfreeze_regex else None
    gate_params, extra_params = _trainable_params(model, unfreeze_patterns, unfreeze_regex)
    if not gate_params and not args.allow_no_gates:
        raise RuntimeError("no trainable global_gates found")
    if not gate_params and args.allow_no_gates:
        print("[WARN] no trainable global_gates found; training only extra unfrozen params.", flush=True)
    if not gate_params and not extra_params:
        raise RuntimeError("no trainable params found (both global_gates and extra params are empty)")
    if extra_params:
        print(f"Unfreezing extra params: {len(extra_params)} tensors", flush=True)
    optimizer_params = []
    if gate_params:
        optimizer_params.append({"params": gate_params, "lr": args.lr})
    if extra_params:
        optimizer_params.append({"params": extra_params, "lr": args.lr_unfreeze})
    optimizer = torch.optim.AdamW(optimizer_params, weight_decay=0.0)

    best_val = None
    for epoch in range(1, args.epochs + 1):
        model.train()
        running = 0.0
        for vi, ir in train_loader:
            vi = vi.to(device, non_blocking=True)
            ir = ir.to(device, non_blocking=True)
            fused = model(ir, vi)
            loss, loss_i, loss_g, loss_s = fusion_loss(
                fused, ir, vi, args.w_intensity, args.w_grad, args.w_smooth, args.smooth_k
            )
            if args.w_scale > 0:
                lr_h = max(8, int(round(ir.shape[-2] * args.scale_ratio)))
                lr_w = max(8, int(round(ir.shape[-1] * args.scale_ratio)))
                lr_h, lr_w = _adjust_crop_size((lr_h, lr_w))
                ir_lr = F.interpolate(ir, size=(lr_h, lr_w), mode="bilinear", align_corners=False)
                vi_lr = F.interpolate(vi, size=(lr_h, lr_w), mode="bilinear", align_corners=False)
                fused_lr = model(ir_lr, vi_lr)
                loss = loss + args.w_scale * scale_consistency_loss(
                    fused, fused_lr, edge_weight=args.scale_edge_weight
                )
            gate_reg = _gate_l2(model)
            if gate_reg is not None and args.w_gate > 0:
                loss = loss + args.w_gate * gate_reg
            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            optimizer.step()
            running += loss.item()

        avg_train = running / max(1, len(train_loader))

        model.eval()
        val_running = 0.0
        with torch.no_grad():
            for vi, ir in val_loader:
                vi = vi.to(device, non_blocking=True)
                ir = ir.to(device, non_blocking=True)
                fused = model(ir, vi)
                loss, _, _, _ = fusion_loss(
                    fused, ir, vi, args.w_intensity, args.w_grad, args.w_smooth, args.smooth_k
                )
                if args.w_scale > 0:
                    lr_h = max(8, int(round(ir.shape[-2] * args.scale_ratio)))
                    lr_w = max(8, int(round(ir.shape[-1] * args.scale_ratio)))
                    lr_h, lr_w = _adjust_crop_size((lr_h, lr_w))
                    ir_lr = F.interpolate(ir, size=(lr_h, lr_w), mode="bilinear", align_corners=False)
                    vi_lr = F.interpolate(vi, size=(lr_h, lr_w), mode="bilinear", align_corners=False)
                    fused_lr = model(ir_lr, vi_lr)
                    loss = loss + args.w_scale * scale_consistency_loss(
                        fused, fused_lr, edge_weight=args.scale_edge_weight
                    )
                gate_reg = _gate_l2(model)
                if gate_reg is not None and args.w_gate > 0:
                    loss = loss + args.w_gate * gate_reg
                val_running += loss.item()
        avg_val = val_running / max(1, len(val_loader))

        print(f"epoch {epoch}/{args.epochs} - train {avg_train:.6f} - val {avg_val:.6f}")

        is_best = best_val is None or avg_val < best_val
        if is_best:
            best_val = avg_val

        if args.save_every > 0 and epoch % args.save_every == 0:
            torch.save({"model": model.state_dict(), "epoch": epoch, "optimizer": optimizer.state_dict()}, args.save_path)

    torch.save({"model": model.state_dict(), "epoch": args.epochs, "optimizer": optimizer.state_dict()}, args.save_path)
    print(f"saved: {args.save_path}")


if __name__ == "__main__":
    main()
